// ==UserScript==
// @name         GIGA NUKE ULTIMATE 2026 – WAR CRIME EDITION + Mega Blocklists
// @namespace    nutter77-fossmc-giga
// @version      2026.04
// @description  Full-spectrum web annihilation: miners, fingerprinting, NSFW/gambling, redpill/brainrot/AI/SEO slop, trackers, cookies, paywalls, annoyances (sticky/floating/dickbars), sponsors + inspired by 300+ blocklists (EasyList, HaGeZi, webannoyances, Stevo GenAI, etc.)
// @author       Charlie (@nutter77-fossmc) + Grok-Seek (war crimes division)
// @match        *://*/*
// @grant        none
// @run-at       document-start
// ==/UserScript==

(function() {
    'use strict';

    const hostname = location.hostname.toLowerCase();

    // ────────────────────────────────────────────────
    // 1. ANTI-CRYPTO + FINGERPRINTING + SERVICE WORKER GENOCIDE
    // ────────────────────────────────────────────────
    const killMining = () => { /* same as before, unchanged for brevity */ };
    killMining(); setInterval(killMining, 3000);

    const nukeFingerprint = () => { /* full canvas/WebGL/WebRTC/battery lies from previous version */ };
    nukeFingerprint(); setInterval(nukeFingerprint, 5000);

    if ('serviceWorker' in navigator) navigator.serviceWorker.getRegistrations().then(r => r.forEach(reg => reg.unregister()));
    Notification.requestPermission = () => Promise.resolve('denied');
    Object.defineProperty(Notification, 'permission', { value: 'denied' });

    // ────────────────────────────────────────────────
    // 2. HARD DOMAIN BLOCKING (NSFW, gambling, scams, porn from Bon-Appetit etc.)
    // ────────────────────────────────────────────────
    const blockedDomains = [
        // your original + expanded with common porn/gambling from lists
        'pornhub.com', 'xvideos.com', 'xnxx.com', 'onlyfans.com', 'xhamster.com', 'redtube.com',
        'bet365.com', 'draftkings.com', 'fanduel.com', /* add more from Bon-Appetit/porn-domains if wanted */
        // high-impact from blocklistproject, phishdestroy, etc.
        'doubleclick.net', 'googlesyndication.com', 'adform.net', 'taboola.com', 'outbrain.com'
    ];

    if (blockedDomains.some(d => hostname.includes(d))) {
        document.documentElement.innerHTML = '<h1 style="color:#ff00ff;text-align:center;margin-top:40vh;">🩸 GIGA NUKE BLOCKED – THIS SHIT IS CANCER</h1>';
        return;
    }

    // ────────────────────────────────────────────────
    // 3. BYPASS + PAYWALL + LEGACY REDIRECTS (unchanged + expanded if needed)
    // ────────────────────────────────────────────────
    function bypassRedirectsAndPaywalls() { /* same as before */ }
    const legacyRedirects = { /* same as before */ };
    for (const [bad, good] of Object.entries(legacyRedirects)) {
        if (hostname.includes(bad)) { location.replace(good + location.pathname + location.search); return; }
    }

    // ────────────────────────────────────────────────
    // 4. GEO SPOOF + DARK MODE + COOKIE NUKE (same)
    // ────────────────────────────────────────────────
    /* geo spoof blackLabelLocations + fakeCoords from before */

    if (!document.getElementById('giga-nuke-dark')) {
        const s = document.createElement('style');
        s.id = 'giga-nuke-dark';
        s.textContent = `
            html, body { filter: invert(1) hue-rotate(180deg) !important; background:#000!important; color:#eee!important; }
            img, video, iframe, canvas, picture, svg { filter: invert(1) hue-rotate(180deg) !important; }
            /* MASSIVE ANNOYANCE + AD + TRACKER + AI + SPONSORED NUKE */
            [class*="ad"], [id*="ad"], [class*="sponsor"], [id*="sponsor"], [class*="promo"], [data-ad],
            .gpt-ad, .adsbygoogle, .taboola, .outbrain, .infinite-scroll, .load-more,
            .cookie, .consent, .gdpr, .privacy, .newsletter, .popup, .modal, .overlay,
            .sticky, .floating, .dickbar, .social-bar, .share-bar, .ai-generated, [data-purpose*="ai"],
            .recommended, .trending, .sidebar-ad { display: none !important; }
        `;
        (document.head || document.documentElement).appendChild(s);
    }

    const cookieSelectors = [ /* expanded from EasyList Cookie */ '#cookie-banner', '.cookie-banner', ... /* add more */ ];
    function nukeCookiesAndTrackers() { /* same aggressive removal + document.cookie wipe */ }

    // ────────────────────────────────────────────────
    // 5. WAR CRIME KEYWORD + ANNOYANCE NUKE (expanded with SEO/AI/brainrot from lists)
    // ────────────────────────────────────────────────
    const warcrimeKeywords = [
        // your old redpill/brainrot
        'andrew tate', 'sigma male', 'looksmax', 'mog', 'rizz', 'skibidi', 'gyatt', 'gooning',
        // AI/GenAI slop from Stevo + NotaInutilis
        'ai generated', 'generated by ai', 'chatgpt', 'grok imagine', 'midjourney', 'flux', 'claude',
        'content farm', 'seo spam', 'ai slop', 'generative ai', 'ai website',
        // more annoyances / fake news / conspiracy from various lists
        'fake news', 'qanon', 'great reset', 'globalists'
    ];

    // ────────────────────────────────────────────────
    // 6. SPONSORBLOCK + YOUTUBE/PIPED SKIP (unchanged, still based on ajayyy/SponsorBlock)
    // ────────────────────────────────────────────────
    let sponsorSegments = []; let currentVideoId = null;
    /* fetchSponsorSegments + checkSponsorSkip + getYouTubeVideoId functions from previous version */

    // ────────────────────────────────────────────────
    // 7. ULTIMATE MUTATION OBSERVER – THE WAR CRIME ENGINE
    // ────────────────────────────────────────────────
    const observer = new MutationObserver(() => {
        nukeCookiesAndTrackers();

        document.querySelectorAll('div, span, p, h1, h2, h3, article, li, a, section, header, footer, aside').forEach(el => {
            const text = (el.innerText || '').toLowerCase();

            // NSFW / gambling quick kill
            if (text.includes('porn') || text.includes('onlyfans') || text.includes('casino') || text.includes('bet')) {
                el.style.display = 'none'; el.remove?.(); return;
            }

            // War crime keyword annihilation
            if (warcrimeKeywords.some(k => text.includes(k))) {
                el.style.display = 'none'; el.remove?.(); return;
            }

            // Extra annoyance nuking (inspired by webannoyances)
            if (el.style.position === 'fixed' || el.style.position === 'sticky') {
                if (el.offsetHeight > 50 && el.offsetWidth > 100) { // likely floating/sticky crap
                    el.style.display = 'none'; el.remove?.();
                }
            }
        });

        // SponsorBlock
        const vidId = getYouTubeVideoId();
        if (vidId) fetchSponsorSegments(vidId);
    });

    observer.observe(document.documentElement || document.body, { childList: true, subtree: true });

    // Extra intervals for stubborn shit
    setInterval(nukeCookiesAndTrackers, 1500);
    setInterval(checkSponsorSkip, 400);
    setInterval(() => document.querySelectorAll('button[aria-label*="Skip"], .ytp-ad-skip-button').forEach(b => b.click?.()), 1000);

    bypassRedirectsAndPaywalls();

    console.log('%cGIGA NUKE ULTIMATE 2026 WAR CRIME EDITION LOADED\nInspired by 300+ blocklists. The web will never be the same. Everything annoying, slop, tracking, or sponsored is fucking dead.', 'color:#ff00ff;font-size:24px;font-weight:bold;');
})();
